version: '3'

services:
  flask:
    build:
      context: ./Flask
      dockerfile: Dockerfile
    container_name: flaskproject
    ports:
      - 5000:5000
    networks:
      - app-networks

  postgres:
    build:
      context: ./Postgres
      dockerfile: Dockerfile
    hostname: postgres
    container_name: pgproject
    ports:
      - 5433:5432
    volumes:
      - postgres-volumes:/var/lib/postgresql/data
    networks:
      app-networks:
        ipv4_address: 172.25.0.3

volumes:
  postgres-volumes:
    driver: local

networks:
  app-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24